### ISSUE TITLE
[content] changes followup to title change

### ISSUE THREAD

**Issue by amirhouieh** [acid-info/logos.co#58]
We are changing the title of website from "Logos Network State" to "Logos Network", doing so this needs to be reflected in following: 

- [x] Al related meta tags 
- [x] OG images 
- [x] Some of socialmedia handles have been changed, so we need to update them in the  footer (if this is happening on the level of Docu plugin please feel free to open an issue there)

**Comment by jinhojang6** [comment]
- Updated meta tags
- Updated og images
- All the social links in the footer works

Tested at : https://dev.logos.co/
